### ISSUE TITLE
看起来我是缺少某些库

### ISSUE THREAD

**Issue by nocmt** [manateelazycat/deepin-picker#1]
$ qmake ..

    update: could not exec '/usr/lib/x86_64-linux-gnu/qt5/bin/lupdate': No such file or directory
    lrelease: could not exec '/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease': No such file or directory

**Comment by manateelazycat** [comment]
andy@andy-PC:~$ apt-file search qt5/bin/lupdate
qttools5-dev-tools: /usr/lib/x86_64-linux-gnu/qt5/bin/lupdate


善用 apt-file 这个工具，自己动手丰衣足食。 ;)
